import {createRemoteJWKSet,jwtVerify} from 'jose';
import {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse} from '@simplewebauthn/server';
import {ApiError} from './repository.js';
export const ttl=30*24*3600;
export const random=()=>crypto.randomUUID()+crypto.randomUUID();
export async function hash(s){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,'0')).join('');}
const jwks=new Map();
export async function accessIdentity(request,env){if(!env.ACCESS_TEAM||!env.ACCESS_AUD)throw new ApiError(503,'首次登入服務尚未啟用。');const team=env.ACCESS_TEAM;if(!/^[a-z0-9-]+$/.test(team))throw new ApiError(503,'登入服務配置錯誤。');const token=request.headers.get('Cf-Access-Jwt-Assertion');if(!token)throw new ApiError(401,'請先驗證 Email。');if(!jwks.has(team))jwks.set(team,createRemoteJWKSet(new URL(`https://${team}.cloudflareaccess.com/cdn-cgi/access/certs`)));try{const {payload}=await jwtVerify(token,jwks.get(team),{issuer:`https://${team}.cloudflareaccess.com`,audience:env.ACCESS_AUD,algorithms:['RS256']});if(typeof payload.email!=='string'||payload.type!=='app')throw new Error();return payload.email.toLowerCase();}catch{throw new ApiError(401,'登入驗證失敗。');}}
export class AuthStore{
 constructor(ctx){this.ctx=ctx;}
 async fetch(req){const {op,key,value}=await req.json();let result;
 if(op==='get')result=await this.ctx.storage.get(key);
 else if(op==='put'){await this.ctx.storage.put(key,value);await this.ctx.storage.setAlarm(Date.now()+86400000);result=true;}
 else if(op==='delete'){result=await this.ctx.storage.delete(key);}
 else if(op==='consume'){result=await this.ctx.storage.transaction(async tx=>{const v=await tx.get(key);await tx.delete(key);return v;});}
 else if(op==='rate'){result=await this.ctx.storage.transaction(async tx=>{const now=Date.now();let v=await tx.get(key);if(!v||v.expires<now)v={count:0,expires:now+600000};v.count++;await tx.put(key,v);return v.count<=30;});}
 else if(op==='credential'){result=await this.ctx.storage.transaction(async tx=>{const list=await tx.get(key)||[];if(list.some(c=>c.id===value.id))throw new Error('Duplicate credential');list.push(value);await tx.put(key,list);return true;});}
 else if(op==='counter'){result=await this.ctx.storage.transaction(async tx=>{const list=await tx.get(key)||[];const c=list.find(c=>c.id===value.id);if(!c||c.counter!==value.previous)return false;c.counter=value.counter;await tx.put(key,list);return true;});}
 else return new Response('invalid',{status:400});
 return Response.json({value:result??null});
 }
 async alarm(){const entries=await this.ctx.storage.list();const expired=[...entries].filter(([key,v])=>v?.expires&&v.expires<Date.now()).map(([key])=>key);if(expired.length)await this.ctx.storage.delete(expired);await this.ctx.storage.setAlarm(Date.now()+86400000);}
}
export async function state(env,op,key,value){const id=env.AUTH_STORE.idFromName('westar-auth-v1');const r=await env.AUTH_STORE.get(id).fetch('https://internal/',{method:'POST',body:JSON.stringify({op,key,value})});if(!r.ok)throw new ApiError(503,'登入狀態暫時無法讀取。');return (await r.json()).value;}
export async function session(env,email){const token=random(),expires=Date.now()+ttl*1000;await state(env,'put','session:'+await hash(token),{email,expires});return token;}
export async function authenticated(req,env,repo){const token=req.headers.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token||token.length>200)throw new ApiError(401,'請先登入。');const value=await state(env,'get','session:'+await hash(token));if(!value||value.expires<Date.now()){if(value)await state(env,'delete','session:'+await hash(token));throw new ApiError(401,'登入已過期。');}const member=await repo.member(value.email);return {member,token};}
const encode=b=>btoa(String.fromCharCode(...b));const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export async function passkey(path,body,env,repo,request){const expectedOrigin=env.API_ORIGIN;if(!expectedOrigin)throw new ApiError(503,'Passkey 尚未配置。');const rpID=new URL(expectedOrigin).hostname;
 if(path==='register-options'){const {member}=await authenticated(request,env,repo);const credentials=await state(env,'get','credentials:'+member.email)||[];const options=await generateRegistrationOptions({rpName:'WESTAR Proposal Desk',rpID,userName:member.email,userID:new TextEncoder().encode(await hash(member.email)),attestationType:'none',excludeCredentials:credentials.map(c=>({id:c.id,transports:c.transports})),authenticatorSelection:{residentKey:'required',userVerification:'required'}});const challenge_id=random();await state(env,'put','challenge:'+challenge_id,{challenge:options.challenge,email:member.email,kind:'register',expires:Date.now()+300000});return {options,challenge_id};}
 if(path==='register-verify'){const {member}=await authenticated(request,env,repo);const c=await state(env,'consume','challenge:'+body.challenge_id);if(!c||c.kind!=='register'||c.email!==member.email||c.expires<Date.now())throw new ApiError(400,'驗證已過期，請重試。');let verification;try{verification=await verifyRegistrationResponse({response:body.response,expectedChallenge:c.challenge,expectedOrigin,expectedRPID:rpID,requireUserVerification:true});}catch{throw new ApiError(400,'Passkey 驗證失敗。');}if(!verification.verified||!verification.registrationInfo)throw new ApiError(400,'Passkey 驗證失敗。');const {credential,credentialDeviceType,credentialBackedUp}=verification.registrationInfo;await state(env,'credential','credentials:'+member.email,{...credential,publicKey:encode(credential.publicKey),credentialDeviceType,credentialBackedUp});return {ok:true};}
 if(path==='login-options'){const email=String(body.email||'').toLowerCase().trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new ApiError(400,'請輸入 Email。');const credentials=await state(env,'get','credentials:'+email)||[];const options=await generateAuthenticationOptions({rpID,userVerification:'required',allowCredentials:credentials.length?credentials.map(c=>({id:c.id,transports:c.transports})):[]});const challenge_id=random();await state(env,'put','challenge:'+challenge_id,{challenge:options.challenge,email,kind:'login',expires:Date.now()+300000});return {options,challenge_id};}
 if(path==='login-verify'){const c=await state(env,'consume','challenge:'+body.challenge_id);if(!c||c.kind!=='login'||c.expires<Date.now())throw new ApiError(400,'驗證已過期，請重試。');const credentials=await state(env,'get','credentials:'+c.email)||[];const credential=credentials.find(x=>x.id===body.response?.id);if(!credential)throw new ApiError(401,'Passkey 登入失敗。');let verification;try{verification=await verifyAuthenticationResponse({response:body.response,expectedChallenge:c.challenge,expectedOrigin,expectedRPID:rpID,credential:{...credential,publicKey:decode(credential.publicKey)},requireUserVerification:true});}catch{throw new ApiError(401,'Passkey 登入失敗。');}if(!verification.verified)throw new ApiError(401,'Passkey 登入失敗。');await repo.member(c.email);const ok=await state(env,'counter','credentials:'+c.email,{id:credential.id,previous:credential.counter,counter:verification.authenticationInfo.newCounter});if(!ok)throw new ApiError(409,'請重新驗證。');return {token:await session(env,c.email)};}
 throw new ApiError(404,'找不到此操作。');
}
