import {validateProposal,verifyContentHash,statuses} from './schema.js';
export class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}
const enc=s=>btoa(String.fromCharCode(...new TextEncoder().encode(s)));
const dec=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\n/g,'')),c=>c.charCodeAt(0)));
export class Repository{
 constructor(env,fetcher=(input,init)=>fetch(input,init)){this.env=env;this.fetcher=fetcher;}
 async request(path,opts={}){if(!this.env.GITHUB_TOKEN)throw new ApiError(503,'私有資料服務尚未配置。');const r=await this.fetcher(`https://api.github.com/repos/whiletrue247/westar-intel/${path}`,{...opts,headers:{Authorization:`Bearer ${this.env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'westar-proposal-desk',...(opts.body?{'Content-Type':'application/json'}:{})},cache:'no-store'});if(!r.ok)throw new ApiError(r.status===404?404:r.status===409||r.status===422?409:503,r.status===404?'找不到提案。':r.status===409||r.status===422?'資料已更新，請重新整理後再操作。':'私有資料暫時無法讀取。');return r.json();}
 async file(path){const d=await this.request('contents/'+path+'?ref=main');if(!d.content)throw new ApiError(503,'資料格式不正確。');return {value:JSON.parse(dec(d.content)),sha:d.sha};}
 async member(email){const {value}=await this.file('auth/members.json');const m=value.members.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.active);if(!m||!['owner','reviewer','viewer'].includes(m.role))throw new ApiError(403,'此 Email 尚未受邀。');return m;}
 async proposal(id){const f=await this.file(`proposals/${id}.json`);validateProposal(f.value);await verifyContentHash(f.value);return f;}
 async list(){const index=await this.file('index.json');if(!Array.isArray(index.value.proposal_ids))throw new ApiError(503,'索引格式不正確。');const all=await Promise.all(index.value.proposal_ids.map(id=>this.proposal(id)));return all.map(({value:p})=>({proposal_id:p.proposal_id,account:p.account,title:p.title,created_at:p.created_at,updated_at:p.updated_at,version:p.version,status:p.status}));}
 async status(id,body,member){if(!['owner','reviewer'].includes(member.role))throw new ApiError(403,'此成員僅可閱讀。');if(!statuses.has(body.status)||!Number.isSafeInteger(body.version))throw new ApiError(400,'狀態或版本不正確。');const f=await this.proposal(id),p=f.value;if(p.version!==body.version)throw new ApiError(409,'資料已更新，請重新整理後再操作。');if(p.status===body.status)return p;const updated_at=new Date().toISOString();const next={...p,status:body.status,updated_at,version:p.version+1,history:[...p.history,{version:p.version+1,updated_at,kind:'status',status:body.status,actor:member.email,content_sha256:p.source.sha256}]};validateProposal(next);await this.request(`contents/proposals/${id}.json`,{method:'PUT',body:JSON.stringify({message:`Update ${id} status to ${body.status}`,branch:'main',sha:f.sha,content:enc(JSON.stringify(next,null,2)+'\n')})});return next;}
}
