import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtemp,writeFile,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {validateProposal,verifyContentHash} from '../backend/schema.js';import {Repository} from '../backend/repository.js';import {AuthStore,authenticated,session,state,passkey,hash} from '../backend/auth.js';import worker from '../backend/worker.js';
const content='A formal assistant proposal.\n\nLiteral <script>alert(1)</script> is text.';
function proposal(){return {marker:'WESTAR_PROPOSAL',proposal_id:'test-award-2027',account:'Example company',title:'Example award',created_at:'2026-10-07T00:00:00Z',updated_at:'2026-10-07T00:00:00Z',version:1,status:'review',content,mail:{to:'reader@example.com',subject:'Award & venue? 合作',body:'First line\n第二行 & symbols?#'},source:{role:'assistant',kind:'final_proposal',action:'publish',conversation_id:'example-source',message_id:'assistant-final',sha256:createHash('sha256').update(content).digest('hex')},history:[{version:1,kind:'proposal',updated_at:'2026-10-07T00:00:00Z'}]};}
const encode=x=>Buffer.from(JSON.stringify(x)).toString('base64');
function fakeRepository(){let p=proposal(),sha='initial';const members={members:[{email:'owner@example.com',role:'owner',active:true},{email:'viewer@example.com',role:'viewer',active:true}]};const fetcher=async(url,opts)=>{assert.ok(url.startsWith('https://api.github.com/repos/whiletrue247/westar-intel/'));assert.equal(opts.headers.Authorization,'Bearer backend-secret');if(url.includes('auth/members.json'))return Response.json({content:encode(members),sha:'members'});if(url.includes('index.json'))return Response.json({content:encode({proposal_ids:[p.proposal_id]}),sha:'index'});if(opts.method==='PUT'){const data=JSON.parse(opts.body);if(data.sha!==sha)return Response.json({}, {status:409});p=JSON.parse(Buffer.from(data.content,'base64').toString());sha='newsha';return Response.json({commit:{sha}});}return Response.json({content:encode(p),sha});};return {repo:new Repository({GITHUB_TOKEN:'backend-secret'},fetcher),members,get:()=>p};}
function authEnv(){const data=new Map();const storage={get:async k=>data.get(k),put:async(k,v)=>data.set(k,structuredClone(v)),delete:async k=>Array.isArray(k)?k.map(x=>data.delete(x)):data.delete(k),transaction:async cb=>cb(storage),setAlarm:async()=>{},getAlarm:async()=>null,list:async()=>data};const store=new AuthStore({storage});return {API_ORIGIN:'https://api.example.com',FRONTEND_ORIGIN:'https://whiletrue247.github.io',AUTH_STORE:{idFromName:()=> 'internal',get:()=>({fetch:async(url,init)=>store.fetch(new Request(url,init))})}};}
test('Thin Proposal boundary admits freeform content but rejects unsafe envelopes',async()=>{for(const change of [{proposal_id:'../auth'},{content:''},{messages:[]},{status:'invented'},{version:0},{mail:[]},{history:{}}])assert.throws(()=>validateProposal({...proposal(),...change}));assert.equal(validateProposal({proposal_id:'minimal-proposal',content:'# Any narrative structure'}).content,'# Any narrative structure');assert.equal(validateProposal(proposal()).content,content);await verifyContentHash(proposal());await assert.rejects(verifyContentHash({...proposal(),content:'changed'}));});
test('No login / forged bearer / wrong CORS origin cannot read or mutate proposals',async()=>{const env=authEnv();for(const path of ['/api/proposals','/api/proposals/test-award-2027','/api/proposals/test-award-2027/status']){const r=await worker.fetch(new Request('https://api.example.com'+path),env);assert.equal(r.status,401);assert.equal((await r.json()).error,'請先登入。');assert.equal(r.headers.get('Cache-Control'),'no-store, private');}const forged=await worker.fetch(new Request('https://api.example.com/api/proposals',{headers:{Authorization:'Bearer forged'}}),env);assert.equal(forged.status,401);const wrong=await worker.fetch(new Request('https://api.example.com/api/proposals',{headers:{Origin:'https://attacker.example'}}),env);assert.equal(wrong.status,403);assert.equal(wrong.headers.get('Access-Control-Allow-Origin'),null);});
test('Email allowlist denies strangers and revoked members',async()=>{const {repo,members}=fakeRepository();await assert.rejects(repo.member('stranger@example.com'),e=>e.status===403);assert.equal((await repo.member('OWNER@example.com')).role,'owner');members.members[0].active=false;await assert.rejects(repo.member('owner@example.com'),e=>e.status===403);});
test('Authenticated owner reads list and exact detail; status write preserves original text and conflict checks',async()=>{const {repo,get}=fakeRepository();const list=await repo.list();assert.equal(list.length,1);assert.equal(list[0].content,undefined);const detail=await repo.proposal('test-award-2027');assert.equal(detail.value.content,content);const updated=await repo.status('test-award-2027',{status:'waiting',version:1},{email:'owner@example.com',role:'owner'});assert.equal(updated.version,2);assert.equal(updated.content,content);await verifyContentHash(updated);assert.equal(get().status,'waiting');await assert.rejects(repo.status('test-award-2027',{status:'sent',version:1},{role:'owner'}),e=>e.status===409);await assert.rejects(repo.status('test-award-2027',{status:'sent',version:2},{role:'viewer'}),e=>e.status===403);assert.equal((await repo.list())[0].version,2);});
test('Long session stores hash only; expiry, logout and allowlist revocation work',async()=>{const env=authEnv(),{repo,members}=fakeRepository();const token=await session(env,'owner@example.com');const key='session:'+await hash(token),stored=await state(env,'get',key);assert.equal(stored.token,undefined);assert.ok(stored.expires>Date.now()+29*86400000);const req=new Request('https://api.example.com/api/proposals',{headers:{Authorization:`Bearer ${token}`}});assert.equal((await authenticated(req,env,repo)).member.role,'owner');members.members[0].active=false;await assert.rejects(authenticated(req,env,repo),e=>e.status===403);members.members[0].active=true;await state(env,'delete',key);await assert.rejects(authenticated(req,env,repo),e=>e.status===401);await state(env,'put',key,{email:'owner@example.com',expires:Date.now()-1});await assert.rejects(authenticated(req,env,repo),e=>e.status===401);});
test('Passkey registration requires login; challenge cannot be replayed',async()=>{const env=authEnv(),{repo}=fakeRepository();const req=new Request('https://api.example.com/api/passkey/register-options');await assert.rejects(passkey('register-options',{},env,repo,req),e=>e.status===401);await state(env,'put','challenge:test',{challenge:'challenge',email:'owner@example.com',kind:'login',expires:Date.now()+300000});assert.equal((await state(env,'consume','challenge:test')).challenge,'challenge');assert.equal(await state(env,'consume','challenge:test'),null);await assert.rejects(passkey('login-verify',{challenge_id:'test',response:{}},env,repo,req),e=>e.status===400);});
test('Unauthenticated auth endpoint fails closed before onboarding configuration',async()=>{const r=await worker.fetch(new Request('https://api.example.com/auth/start?state=12345678-1234-1234-1234-123456789abc'),authEnv());assert.equal(r.status,503);assert.ok(!(await r.text()).includes('token'));});
test('Importer preserves bytes, same ID increments version, and chat import is refused',async()=>{const dir=await mkdtemp(join(tmpdir(),'westar-publish-test-')),input=join(dir,'input.json'),target=join(dir,'private');await mkdir(target);await writeFile(join(target,'.westar-intel.json'),JSON.stringify({repository:'whiletrue247/westar-intel',visibility:'private'}));const p=proposal();await writeFile(input,JSON.stringify(p));let result=spawnSync(process.execPath,['scripts/publish-proposal.js',input,target],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);const saved=JSON.parse(await readFile(join(target,'proposals',p.proposal_id+'.json'),'utf8'));assert.equal(saved.content,p.content);assert.equal(saved.version,1);await writeFile(input,JSON.stringify({...p,expected_version:1}));result=spawnSync(process.execPath,['scripts/publish-proposal.js',input,target],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(await readFile(join(target,'proposals',p.proposal_id+'.json'),'utf8')).version,2);const noMail={...p,proposal_id:'test-no-email-proposal',account:'No email account',mail:{available:false,reason:'No verified public email.'}};await writeFile(input,JSON.stringify(noMail));result=spawnSync(process.execPath,['scripts/publish-proposal.js',input,target],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);const noMailSaved=JSON.parse(await readFile(join(target,'proposals',noMail.proposal_id+'.json'),'utf8'));assert.equal(noMailSaved.mail.available,false);assert.equal(noMailSaved.mail.archival_placeholder,true);assert.equal(noMailSaved.mail.to,'archive@westar.invalid');await writeFile(input,JSON.stringify({messages:[{role:'user',content:'do not publish'}]}));result=spawnSync(process.execPath,['scripts/publish-proposal.js',input,target],{encoding:'utf8'});assert.notEqual(result.status,0);});
test('Frontend contains no proposals, credential constants, API mail sending or unsafe HTML rendering',async()=>{const text=await readFile('web/app.js','utf8');assert.ok(!text.includes('innerHTML'));for(const name of ['index.html','app.js','config.js','style.css']){const source=await readFile('web/'+name,'utf8');assert.ok(!/gho_[A-Za-z0-9]+|github_pat_|GITHUB_TOKEN|service_role|supabase|gmail\.googleapis\.com/.test(source));}const fn=text.match(/export function mailto\(mail\)\{([^\n]+)\}/)[1];const make=new Function('mail',fn);const mail=proposal().mail,url=new URL(make(mail));assert.equal(decodeURIComponent(url.pathname),mail.to);assert.equal(url.searchParams.get('subject'),mail.subject);assert.equal(url.searchParams.get('body'),mail.body.replace(/\n/g,'\r\n'));});
test('Google code flow uses PKCE and nonce, binds state to browser cookie, and consumes state only once',async()=>{const {googleStart,googleCallback}=await import('../backend/google.js');const env={...authEnv(),GOOGLE_CLIENT_ID:'example.apps.googleusercontent.com',GOOGLE_CLIENT_SECRET:'backend-only-test-secret'};const r=await googleStart(new Request('https://api.example.com/auth/start?state=12345678-1234-1234-1234-123456789abc'),env);assert.equal(r.status,302);const url=new URL(r.headers.get('Location'));assert.equal(url.origin,'https://accounts.google.com');assert.equal(url.searchParams.get('scope'),'openid email');assert.equal(url.searchParams.get('response_type'),'code');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.ok(url.searchParams.get('nonce'));assert.ok(!url.href.includes(env.GOOGLE_CLIENT_SECRET));assert.equal(url.searchParams.get('redirect_uri'),'https://api.example.com/auth/google/callback');assert.match(r.headers.get('Set-Cookie'),/Secure; HttpOnly; SameSite=Lax/);const oauthState=url.searchParams.get('state'),callbackURL=`https://api.example.com/auth/google/callback?state=${oauthState}&error=access_denied`;await assert.rejects(googleCallback(new Request(callbackURL),env,{}),e=>e.status===400);const cookie=r.headers.get('Set-Cookie').split(';')[0];await assert.rejects(googleCallback(new Request(callbackURL,{headers:{Cookie:cookie}}),env,{}),e=>e.status===403);await assert.rejects(googleCallback(new Request(callbackURL,{headers:{Cookie:cookie}}),env,{}),e=>e.status===400);});
test('Google identity signature, audience, issuer, nonce, verified email and expiry are enforced',async()=>{const {generateKeyPair,SignJWT}=await import('jose');const {verifyGoogleIdentity}=await import('../backend/google.js');const {privateKey,publicKey}=await generateKeyPair('RS256');const env={GOOGLE_CLIENT_ID:'our-client'};const make=(payload={},issuer='https://accounts.google.com',audience='our-client',expires='5m')=>new SignJWT({email:'OWNER@example.com',email_verified:true,nonce:'expected',...payload}).setProtectedHeader({alg:'RS256'}).setIssuer(issuer).setAudience(audience).setSubject('google-user-id').setIssuedAt().setExpirationTime(expires).sign(privateKey);assert.equal(await verifyGoogleIdentity(await make(),env,'expected',publicKey),'owner@example.com');for(const token of [await make({nonce:'wrong'}),await make({email_verified:false}),await make({},'https://attacker.example'),await make({},'https://accounts.google.com','wrong-client'),await make({},'https://accounts.google.com','our-client',Math.floor(Date.now()/1000)-5)])await assert.rejects(verifyGoogleIdentity(token,env,'expected',publicKey));const other=await generateKeyPair('RS256');const forged=await new SignJWT({email:'owner@example.com',email_verified:true,nonce:'expected'}).setProtectedHeader({alg:'RS256'}).setIssuer('https://accounts.google.com').setAudience('our-client').setSubject('google-user-id').setExpirationTime('5m').sign(other.privateKey);await assert.rejects(verifyGoogleIdentity(forged,env,'expected',publicKey));});
test('Full API accepts a verified session, returns exact proposal and reads subsequent repo updates',async()=>{const env={...authEnv(),GITHUB_TOKEN:'backend-secret'},fake=fakeRepository();const originalFetch=globalThis.fetch;globalThis.fetch=fake.repo.fetcher;try{const token=await session(env,'owner@example.com'),headers={Authorization:`Bearer ${token}`,Origin:env.FRONTEND_ORIGIN};let r=await worker.fetch(new Request('https://api.example.com/api/proposals',{headers}),env);assert.equal(r.status,200);assert.equal((await r.json()).proposals.length,1);r=await worker.fetch(new Request('https://api.example.com/api/proposals/test-award-2027',{headers}),env);assert.equal((await r.json()).proposal.content,content);r=await worker.fetch(new Request('https://api.example.com/api/proposals/test-award-2027/status',{method:'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({status:'waiting',version:1})}),env);assert.equal(r.status,200);assert.equal((await r.json()).proposal.version,2);r=await worker.fetch(new Request('https://api.example.com/api/proposals',{headers}),env);assert.equal((await r.json()).proposals[0].status,'waiting');fake.members.members[0].active=false;r=await worker.fetch(new Request('https://api.example.com/api/proposals',{headers}),env);assert.equal(r.status,403);}finally{globalThis.fetch=originalFetch;}});
test('Default repository fetch preserves the platform fetch receiver',async()=>{const originalFetch=globalThis.fetch;globalThis.fetch=async function(){assert.ok(!(this instanceof Repository),'platform fetch must not be called with Repository as this');return Response.json({content:encode({members:[{email:'owner@example.com',role:'owner',active:true}]}),sha:'member-sha'});};try{assert.equal((await new Repository({GITHUB_TOKEN:'backend-secret'}).member('owner@example.com')).role,'owner');}finally{globalThis.fetch=originalFetch;}});

test('Proposal formatting uses safe text nodes and raw view preserves exact content',async()=>{const source=await readFile('web/app.js','utf8');const makeNode=(tag,text='')=>({tag,textContent:text,children:[],append(...nodes){this.children.push(...nodes);},replaceChildren(){this.children=[];this.textContent='';},classList:{toggle(){}}});const body=makeNode('div');const document={createTextNode:text=>makeNode('#text',text)};const render=new Function('$','node','document',source.match(/^function renderProposal[^\n]+/m)[0]+';return renderProposal;')(()=>body,makeNode,document);const input='Hello **bold** <script>alert(1)</script> [unsafe](javascript:alert)\n\n[Link](https://example.com)';render(input);const children=body.children.flatMap(p=>p.children);assert.ok(children.some(n=>n.tag==='strong'&&n.textContent==='bold'));assert.ok(children.some(n=>n.tag==='#text'&&n.textContent.includes('<script>')));assert.deepEqual(children.filter(n=>n.tag==='a').map(n=>n.href),['https://example.com']);render(input,true);assert.equal(body.textContent,input);});

test('Proposal reading view hides ChatGPT UI tokens while raw view stays exact',async()=>{const source=await readFile('web/app.js','utf8');const makeNode=(tag,text='')=>({tag,textContent:text,children:[],append(...nodes){this.children.push(...nodes);},replaceChildren(){this.children=[];this.textContent='';},classList:{toggle(){}}});const body=makeNode('div');const document={createTextNode:text=>makeNode('#text',text)};const render=new Function('$','node','document',source.match(/^function renderProposal[^\n]+/m)[0]+';return renderProposal;')(()=>body,makeNode,document);const input='map\n\nMeet entity["organization","Model Entrepreneur Competition","MEC"]. citeturn1search0\n\nurlOfficial pagehttps://officialmec.org/';render(input);const children=body.children.flatMap(p=>p.children),visible=children.map(n=>n.textContent).join('');assert.ok(!visible.includes(''));assert.ok(visible.includes('Model Entrepreneur Competition'));assert.ok(children.some(n=>n.tag==='a'&&n.href==='https://officialmec.org/'));render(input,true);assert.equal(body.textContent,input);});


test('Publisher computes missing content SHA-256 while rejecting an incorrect supplied hash',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'westar-auto-sha-test-')),input=join(dir,'input.json'),target=join(dir,'private');
 await mkdir(target);
 await writeFile(join(target,'.westar-intel.json'),JSON.stringify({repository:'whiletrue247/westar-intel',visibility:'private'}));
 const p=proposal(),source={...p.source};
 delete source.sha256;
 await writeFile(input,JSON.stringify({...p,proposal_id:'auto-sha-test',source}));
 const run=()=>spawnSync(process.execPath,['scripts/publish-proposal.js',input,target],{encoding:'utf8'});
 let result=run();
 assert.equal(result.status,0,result.stderr);
 const stored=JSON.parse(await readFile(join(target,'proposals','auto-sha-test.json'),'utf8'));
 const expected=createHash('sha256').update(p.content,'utf8').digest('hex');
 assert.equal(stored.content,p.content);
 assert.equal(stored.source.sha256,expected);
 assert.equal(stored.history.at(-1).content_sha256,expected);
 await verifyContentHash(stored);
 await writeFile(input,JSON.stringify({...p,proposal_id:'bad-sha-test',source:{...p.source,sha256:'0'.repeat(64)}}));
 result=run();
 assert.notEqual(result.status,0,'Explicitly incorrect hash must not be silently overwritten');
});
