import {config} from './config.js';
const $=id=>document.getElementById(id), labels={review:'待審',sent:'已寄出',waiting:'等待回覆',rejected:'淘汰',cooling:'冷卻'};
const storageKey='westar.session.v1';let token=localStorage.getItem(storageKey),proposals=[],selected=null,user=null,generation=0,pending=null;
const notice=text=>$('notice').textContent=text;
const date=s=>new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});
export function mailto(mail){return `mailto:${encodeURIComponent(mail.to)}?subject=${encodeURIComponent(mail.subject)}&body=${encodeURIComponent(mail.body.replace(/\r?\n/g,'\r\n'))}`;}
function reset(){generation++;token=null;localStorage.removeItem(storageKey);proposals=[];selected=null;user=null;for(const id of ['body','account','title','meta','history','mail-note','sync'])$(id).textContent='';$('list').replaceChildren();$('nav-list').replaceChildren();for(const id of ['mailbody','to','subject'])$(id).value='';$('mailto').removeAttribute('href');$('login').hidden=false;$('desk').hidden=true;$('detail').hidden=true;$('logout').hidden=true;$('identity').textContent='';}
async function api(path,opts={}){if(!config.apiBase)throw new Error('登入服務正在配置，尚未開放提案存取。');const res=await fetch(config.apiBase+path,{...opts,cache:'no-store',headers:{Authorization:`Bearer ${token||''}`,...(opts.body?{'Content-Type':'application/json'}:{}),...opts.headers}});if(res.status===401||res.status===403){reset();throw new Error(res.status===403?'此 Email 尚未受邀或權限已撤銷。':'請重新登入。');}const data=await res.json();if(!res.ok)throw new Error(data.error||'讀取失敗，請稍後重試。');return data;}
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function render(){const nav=proposals.map(p=>{const b=node('button',p.title,'nav-item'+(location.hash.slice(1)===p.proposal_id?' active':''));b.onclick=()=>{location.hash=p.proposal_id;closeNavigation();};return b;});$('nav-list').replaceChildren(...nav);const term=$('search').value.trim().toLowerCase(),status=$('filter').value;const matches=proposals.filter(p=>(!status||p.status===status)&&`${p.account} ${p.title}`.toLowerCase().includes(term));$('list').replaceChildren(...matches.map(p=>{const b=node('button','','card');const content=node('div','');content.append(node('div',p.account,'eyebrow'),node('h2',p.title),node('p',`更新 ${date(p.updated_at)} · v${p.version}`,'small'));b.append(content,node('span',labels[p.status],'badge'));b.addEventListener('click',()=>{location.hash=p.proposal_id;});return b;}));$('empty').hidden=!!matches.length;}
async function load(){const g=++generation;notice('');const data=await api('/api/proposals');if(g!==generation)return;user=data.member;proposals=data.proposals;selected=null;$('identity').textContent=`${user.email} · ${user.role}`;$('logout').hidden=false;$('login').hidden=true;$('desk').hidden=false;$('detail').hidden=true;$('register').hidden=false;$('sync').textContent=`最後讀取 ${date(data.fetched_at)} · ${proposals.length} 份正式提案`;render();await route();}
async function route(){if(!user)return;render();const id=location.hash.slice(1);if(!id){selected=null;$('detail').hidden=true;$('desk').hidden=false;return;}if(!/^[a-z0-9][a-z0-9-]{2,79}$/.test(id))return;const g=++generation;try{const data=await api('/api/proposals/'+encodeURIComponent(id));if(g!==generation)return;selected=data.proposal;$('desk').hidden=true;$('detail').hidden=false;$('account').textContent=selected.account;$('title').textContent=selected.title;$('meta').textContent=`更新 ${date(selected.updated_at)} · v${selected.version} · 建立 ${date(selected.created_at)}`;$('body').textContent=selected.content;$('status').value=selected.status;$('status').disabled=!['owner','reviewer'].includes(user.role);$('to').value=selected.mail.to;$('subject').value=selected.mail.subject;$('mailbody').value=selected.mail.body;$('mailto').href=mailto(selected.mail);$('mail-note').textContent=selected.mail.sent_at?`沿用既有信件 · 已於 ${date(selected.mail.sent_at)} 寄出。重新開啟前請確認是否需要再次聯絡。`:'正式提案附帶的預備信件';$('history').replaceChildren(...selected.history.slice().reverse().map(h=>node('p',`v${h.version} · ${date(h.updated_at)} · ${h.kind==='status'?'狀態更新': '正式提案發布'}${h.status?' · '+labels[h.status]:''}`,'small')));window.scrollTo({top:0});}catch(e){notice(e.message);}}
function login(kind){if(!config.apiBase){notice('登入服務正在配置，尚未開放提案存取。');return;}const state=crypto.randomUUID();const path=kind==='email'?'/auth/start':'/passkey';const popup=window.open(`${config.apiBase}${path}?state=${state}&mode=${kind}`,'westar-auth','width=540,height=720');if(!popup){notice('請允許此網站開啟登入視窗。');return;}pending={state,popup,kind};notice('請在登入視窗完成身分驗證。');}
window.addEventListener('message',async e=>{if(!pending||e.origin!==new URL(config.apiBase).origin||e.source!==pending.popup||e.data?.state!==pending.state)return;if(e.data.type==='westar-ready'&&pending.kind==='register'){e.source.postMessage({type:'westar-enroll',state:pending.state,token},e.origin);return;}if(e.data.type==='westar-auth'&&typeof e.data.token==='string'){token=e.data.token;localStorage.setItem(storageKey,token);pending=null;try{await load();}catch(err){notice(err.message);}}else if(e.data.type==='westar-enrolled'){pending=null;notice('Passkey 已建立，下次可使用 Touch ID、Face ID 或裝置解鎖登入。');}});
$('signin').onclick=()=>login('email');$('passkey').onclick=()=>login('login');$('register').onclick=()=>login('register');$('refresh').onclick=()=>load().catch(e=>notice(e.message));$('search').oninput=render;$('filter').onchange=render;$('back').onclick=()=>{location.hash='';};window.addEventListener('hashchange',route);
$('logout').onclick=async()=>{const old=token;reset();location.hash='';if(old&&config.apiBase)await fetch(config.apiBase+'/api/logout',{method:'POST',headers:{Authorization:`Bearer ${old}`}}).catch(()=>{});notice('已登出。');};
$('status').onchange=async()=>{if(!selected)return;const p=selected;const value=$('status').value;$('status').disabled=true;try{const data=await api('/api/proposals/'+p.proposal_id+'/status',{method:'PATCH',body:JSON.stringify({status:value,version:p.version})});selected=data.proposal;await load();notice('狀態已保存至私有資料來源。');}catch(e){$('status').value=p.status;notice(e.message);}finally{$('status').disabled=!['owner','reviewer'].includes(user?.role);}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('mailbody').value);notice('已複製信件正文。');}catch{notice('無法自動複製，請選取信件正文後複製。');}};
if(token)load().catch(e=>notice(e.message));

const savedTheme=localStorage.getItem('westar.theme');if(savedTheme==='light')document.documentElement.dataset.theme='light';function themeLabel(){$('theme').textContent=document.documentElement.dataset.theme==='light'?'切換深色':'切換淺色';}themeLabel();$('theme').onclick=()=>{const theme=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=theme;localStorage.setItem('westar.theme',theme);themeLabel();};

function closeNavigation(){document.body.classList.remove('mobile-nav-open');$('menu').setAttribute('aria-expanded','false');$('nav-overlay').hidden=true;} $('menu').onclick=()=>{const open=document.body.classList.toggle('mobile-nav-open');$('menu').setAttribute('aria-expanded',String(open));$('nav-overlay').hidden=!open;};$('nav-overlay').onclick=closeNavigation;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeNavigation();});
